# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestrauntInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Location', models.CharField(blank=True, default=b'Unknown', max_length=120)),
                ('Category', models.CharField(blank=True, max_length=120, null=True)),
                ('CreatedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
