# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrauntinfo',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
