# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0003_auto_20180902_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restrauntinfo',
            old_name='slug',
            new_name='Slug',
        ),
    ]
