# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0004_auto_20180902_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restrauntinfo',
            name='Slug',
        ),
    ]
