# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0005_remove_restrauntinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrauntinfo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
